version: '3.4'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: gulp default
    volumes:
      - ./server:/code
      - /code/node_modules
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - SERVER_URL="server:8080"
    command: npm start
    volumes:
      - ./client:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
